"""增加token api调用日志表

Revision ID: 0a120ecdb51e
Revises: 4f274b682415
Create Date: 2025-09-01 10:17:23.618213

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0a120ecdb51e'
down_revision: Union[str, Sequence[str], None] = '4f274b682415'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('api_call_logs',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False, comment='自增ID'),
    sa.Column('caller', sa.String(length=128), nullable=False, comment='调用人'),
    sa.Column('caller_ip', sa.String(length=64), nullable=False, comment='调用者IP'),
    sa.Column('called_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False, comment='调用时间'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('api_call_logs')
    # ### end Alembic commands ###
