"""增加店铺id字段

Revision ID: 0a3e1b4d2ae0
Revises: 694dfe907bad
Create Date: 2025-08-27 10:14:47.063835

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0a3e1b4d2ae0'
down_revision: Union[str, Sequence[str], None] = '694dfe907bad'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('promotion_product', sa.Column('shop_id', sa.String(), nullable=True, comment='店铺ID'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('promotion_product', 'shop_id')
    # ### end Alembic commands ###
