"""update table

Revision ID: 11dd2aa6acd4
Revises: 68431123189a
Create Date: 2025-08-14 08:58:20.547699

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '11dd2aa6acd4'
down_revision: Union[str, Sequence[str], None] = '68431123189a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('sale_content', 'content_id',
               existing_type=sa.VARCHAR(),
               comment='内容唯一ID',
               existing_nullable=False)
    op.alter_column('sale_content', 'promotion_id',
               existing_type=sa.VARCHAR(),
               comment='推广ID',
               existing_nullable=True)
    op.alter_column('sale_content', 'content_type',
               existing_type=sa.VARCHAR(),
               comment='内容类型（视频、图文等）',
               existing_nullable=True)
    op.alter_column('sale_content', 'content_title',
               existing_type=sa.VARCHAR(),
               comment='内容标题',
               existing_nullable=True)
    op.alter_column('sale_content', 'content_cover',
               existing_type=sa.VARCHAR(),
               comment='内容封面图',
               existing_nullable=True)
    op.alter_column('sale_content', 'video_url',
               existing_type=sa.VARCHAR(),
               comment='视频链接',
               existing_nullable=True)
    op.alter_column('sale_content', 'duration',
               existing_type=sa.INTEGER(),
               comment='视频时长（秒）',
               existing_nullable=True)
    op.alter_column('sale_content', 'cover_url',
               existing_type=sa.VARCHAR(),
               comment='视频封面图链接',
               existing_nullable=True)
    op.alter_column('sale_content', 'publish_time',
               existing_type=postgresql.TIMESTAMP(),
               comment='发布时间',
               existing_nullable=True)
    op.alter_column('sale_content', 'author_name',
               existing_type=sa.VARCHAR(),
               comment='作者昵称',
               existing_nullable=True)
    op.alter_column('sale_content', 'author_avatar',
               existing_type=sa.VARCHAR(),
               comment='作者头像链接',
               existing_nullable=True)
    op.alter_column('sale_content', 'author_sec_id',
               existing_type=sa.VARCHAR(),
               comment='作者的sec_id',
               existing_nullable=True)
    op.alter_column('sale_content', 'author_level',
               existing_type=sa.INTEGER(),
               comment='作者等级',
               existing_nullable=True)
    op.alter_column('sale_content', 'author_fans_count',
               existing_type=sa.INTEGER(),
               comment='粉丝数',
               existing_nullable=True)
    op.alter_column('sale_content', 'author_resident',
               existing_type=sa.VARCHAR(),
               comment='作者常驻地',
               existing_nullable=True)
    op.alter_column('sale_content', 'share_url',
               existing_type=sa.VARCHAR(),
               comment='视频分享链接',
               existing_nullable=True)
    op.alter_column('sale_content', 'sales',
               existing_type=sa.INTEGER(),
               comment='销量',
               existing_nullable=True)
    op.alter_column('sale_content', 'format_sales',
               existing_type=sa.VARCHAR(),
               comment='格式化销量（带单位）',
               existing_nullable=True)
    op.alter_column('sale_content', 'sales_amount',
               existing_type=sa.BIGINT(),
               comment='销售额（分）',
               existing_nullable=True)
    op.alter_column('sale_content', 'format_sales_amount',
               existing_type=sa.VARCHAR(),
               comment='格式化销售额（带单位）',
               existing_nullable=True)
    op.alter_column('sale_content', 'like_count',
               existing_type=sa.INTEGER(),
               comment='点赞数',
               existing_nullable=True)
    op.alter_column('sale_content', 'play_count',
               existing_type=sa.BIGINT(),
               comment='播放量',
               existing_nullable=True)
    op.alter_column('sale_content', 'order_conversion_rate',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               comment='下单转化率（百分比小数）',
               existing_nullable=True)
    op.alter_column('sale_content', 'format_order_conversion_rate',
               existing_type=sa.VARCHAR(),
               comment='格式化下单转化率（带百分号）',
               existing_nullable=True)
    op.alter_column('sale_content', 'click_rate',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               comment='点击率（百分比小数）',
               existing_nullable=True)
    op.alter_column('sale_content', 'comment_count',
               existing_type=sa.INTEGER(),
               comment='评论数',
               existing_nullable=True)
    op.alter_column('sale_content', 'share_count',
               existing_type=sa.INTEGER(),
               comment='分享数',
               existing_nullable=True)
    op.alter_column('sale_content', 'pcu',
               existing_type=sa.INTEGER(),
               comment='同时在线人数峰值',
               existing_nullable=True)
    op.alter_column('sale_content', 'is_self_sale',
               existing_type=sa.BOOLEAN(),
               comment='是否为自卖',
               existing_nullable=True)
    op.alter_column('sale_content', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               comment='记录创建时间',
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('sale_content', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               comment=None,
               existing_comment='记录创建时间',
               existing_nullable=True)
    op.alter_column('sale_content', 'is_self_sale',
               existing_type=sa.BOOLEAN(),
               comment=None,
               existing_comment='是否为自卖',
               existing_nullable=True)
    op.alter_column('sale_content', 'pcu',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='同时在线人数峰值',
               existing_nullable=True)
    op.alter_column('sale_content', 'share_count',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='分享数',
               existing_nullable=True)
    op.alter_column('sale_content', 'comment_count',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='评论数',
               existing_nullable=True)
    op.alter_column('sale_content', 'click_rate',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               comment=None,
               existing_comment='点击率（百分比小数）',
               existing_nullable=True)
    op.alter_column('sale_content', 'format_order_conversion_rate',
               existing_type=sa.VARCHAR(),
               comment=None,
               existing_comment='格式化下单转化率（带百分号）',
               existing_nullable=True)
    op.alter_column('sale_content', 'order_conversion_rate',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               comment=None,
               existing_comment='下单转化率（百分比小数）',
               existing_nullable=True)
    op.alter_column('sale_content', 'play_count',
               existing_type=sa.BIGINT(),
               comment=None,
               existing_comment='播放量',
               existing_nullable=True)
    op.alter_column('sale_content', 'like_count',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='点赞数',
               existing_nullable=True)
    op.alter_column('sale_content', 'format_sales_amount',
               existing_type=sa.VARCHAR(),
               comment=None,
               existing_comment='格式化销售额（带单位）',
               existing_nullable=True)
    op.alter_column('sale_content', 'sales_amount',
               existing_type=sa.BIGINT(),
               comment=None,
               existing_comment='销售额（分）',
               existing_nullable=True)
    op.alter_column('sale_content', 'format_sales',
               existing_type=sa.VARCHAR(),
               comment=None,
               existing_comment='格式化销量（带单位）',
               existing_nullable=True)
    op.alter_column('sale_content', 'sales',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='销量',
               existing_nullable=True)
    op.alter_column('sale_content', 'share_url',
               existing_type=sa.VARCHAR(),
               comment=None,
               existing_comment='视频分享链接',
               existing_nullable=True)
    op.alter_column('sale_content', 'author_resident',
               existing_type=sa.VARCHAR(),
               comment=None,
               existing_comment='作者常驻地',
               existing_nullable=True)
    op.alter_column('sale_content', 'author_fans_count',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='粉丝数',
               existing_nullable=True)
    op.alter_column('sale_content', 'author_level',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='作者等级',
               existing_nullable=True)
    op.alter_column('sale_content', 'author_sec_id',
               existing_type=sa.VARCHAR(),
               comment=None,
               existing_comment='作者的sec_id',
               existing_nullable=True)
    op.alter_column('sale_content', 'author_avatar',
               existing_type=sa.VARCHAR(),
               comment=None,
               existing_comment='作者头像链接',
               existing_nullable=True)
    op.alter_column('sale_content', 'author_name',
               existing_type=sa.VARCHAR(),
               comment=None,
               existing_comment='作者昵称',
               existing_nullable=True)
    op.alter_column('sale_content', 'publish_time',
               existing_type=postgresql.TIMESTAMP(),
               comment=None,
               existing_comment='发布时间',
               existing_nullable=True)
    op.alter_column('sale_content', 'cover_url',
               existing_type=sa.VARCHAR(),
               comment=None,
               existing_comment='视频封面图链接',
               existing_nullable=True)
    op.alter_column('sale_content', 'duration',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='视频时长（秒）',
               existing_nullable=True)
    op.alter_column('sale_content', 'video_url',
               existing_type=sa.VARCHAR(),
               comment=None,
               existing_comment='视频链接',
               existing_nullable=True)
    op.alter_column('sale_content', 'content_cover',
               existing_type=sa.VARCHAR(),
               comment=None,
               existing_comment='内容封面图',
               existing_nullable=True)
    op.alter_column('sale_content', 'content_title',
               existing_type=sa.VARCHAR(),
               comment=None,
               existing_comment='内容标题',
               existing_nullable=True)
    op.alter_column('sale_content', 'content_type',
               existing_type=sa.VARCHAR(),
               comment=None,
               existing_comment='内容类型（视频、图文等）',
               existing_nullable=True)
    op.alter_column('sale_content', 'promotion_id',
               existing_type=sa.VARCHAR(),
               comment=None,
               existing_comment='推广ID',
               existing_nullable=True)
    op.alter_column('sale_content', 'content_id',
               existing_type=sa.VARCHAR(),
               comment=None,
               existing_comment='内容唯一ID',
               existing_nullable=False)
    # ### end Alembic commands ###
