"""增加acount_id字段

Revision ID: 1f4fe41ddecf
Revises: a7ecf5004ae2
Create Date: 2025-08-26 17:24:19.236617

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1f4fe41ddecf'
down_revision: Union[str, Sequence[str], None] = 'a7ecf5004ae2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('promotion_product', sa.Column('acount_id', sa.String(), nullable=True, comment='选择该品使用的账号'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('promotion_product', 'acount_id')
    # ### end Alembic commands ###
