"""删除了一些字段

Revision ID: 211c9c139186
Revises: 6b9ad99686a5
Create Date: 2025-09-01 09:34:28.471599

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '211c9c139186'
down_revision: Union[str, Sequence[str], None] = '6b9ad99686a5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('material', sa.Column('is_vertica', sa.Boolean(), nullable=True, comment='是否为竖屏视频'))
    op.alter_column('material', 'usable',
               existing_type=sa.BOOLEAN(),
               comment='该素材是否可以使用',
               existing_comment='是否可以使用',
               existing_nullable=True)
    op.alter_column('material', 'use_status',
               existing_type=sa.BOOLEAN(),
               comment='该素材是否被使用',
               existing_comment='使用状态',
               existing_nullable=True)
    op.drop_column('material', 'is_qianchuan')
    op.add_column('promotion_product', sa.Column('image_list', sa.String(), nullable=True, comment='图片列表'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('promotion_product', 'image_list')
    op.add_column('material', sa.Column('is_qianchuan', sa.BOOLEAN(), autoincrement=False, nullable=True, comment='是否为千川端素材'))
    op.alter_column('material', 'use_status',
               existing_type=sa.BOOLEAN(),
               comment='使用状态',
               existing_comment='该素材是否被使用',
               existing_nullable=True)
    op.alter_column('material', 'usable',
               existing_type=sa.BOOLEAN(),
               comment='是否可以使用',
               existing_comment='该素材是否可以使用',
               existing_nullable=True)
    op.drop_column('material', 'is_vertica')
    # ### end Alembic commands ###
