"""增加user表

Revision ID: 35aaee176c71
Revises: 75b0e2d44116
Create Date: 2025-09-05 14:33:43.873317

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '35aaee176c71'
down_revision: Union[str, Sequence[str], None] = '75b0e2d44116'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('douyin_account',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False, comment='自增ID'),
    sa.Column('aweme_id', sa.String(), nullable=True, comment='抖音ID'),
    sa.Column('qianchuan_id', sa.String(), nullable=True, comment='千川广告主ID'),
    sa.Column('baiying_id', sa.String(), nullable=True, comment='百应选品平台ID'),
    sa.Column('iphone', sa.String(), nullable=True, comment='绑定手机手机号'),
    sa.Column('nickname', sa.String(), nullable=True, comment='抖音昵称'),
    sa.Column('password', sa.String(), nullable=True, comment='抖音登录密码'),
    sa.Column('cooperation_code', sa.String(), nullable=True, comment='合作码'),
    sa.Column('create_at', sa.DateTime(timezone=True), nullable=True, comment='抖音号创建时间'),
    sa.Column('binding_time', sa.DateTime(timezone=True), nullable=True, comment='绑定选品平台的时间'),
    sa.Column('account_status', sa.Integer(), nullable=True, comment='账号状态: 0:不可用; 1:可用; 2:解绑; 3:封禁'),
    sa.Column('account_status_modification_time', sa.DateTime(timezone=True), nullable=True, comment='账号状态修改时间'),
    sa.Column('comment', sa.String(), nullable=True, comment='备注'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('douyin_account')
    # ### end Alembic commands ###
