"""update table

Revision ID: 40f241b3736a
Revises: 11dd2aa6acd4
Create Date: 2025-08-14 12:21:30.704237

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '40f241b3736a'
down_revision: Union[str, Sequence[str], None] = '11dd2aa6acd4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('promotion_product',
    sa.Column('promotion_id', sa.String(), nullable=False, comment='推广ID'),
    sa.Column('product_id', sa.String(), nullable=True, comment='商品ID'),
    sa.Column('product_title', sa.String(), nullable=True, comment='商品名称'),
    sa.Column('product_price', sa.Integer(), nullable=True, comment='到手价，单位为分（使用需要*0.01）'),
    sa.Column('product_cos', sa.Integer(), nullable=True, comment='佣金，单位为分（使用需要*0.01）'),
    sa.Column('good_ratio', sa.Float(), nullable=True, comment='好评率（百分比小数）'),
    sa.Column('product_sales', sa.Integer(), nullable=True, comment='已售'),
    sa.Column('product_match', sa.Integer(), nullable=True, comment='带货人数'),
    sa.Column('shop_name', sa.String(), nullable=True, comment='店铺名称'),
    sa.Column('exper_score', sa.String(), nullable=True, comment='店铺综合得分'),
    sa.Column('goods_score', sa.String(), nullable=True, comment='商品分'),
    sa.Column('logistics_score', sa.String(), nullable=True, comment='物流分'),
    sa.Column('service_score', sa.String(), nullable=True, comment='商家分'),
    sa.Column('sales_amount', sa.Integer(), nullable=True, comment='总销售额，单位为分（使用需要*0.01）'),
    sa.Column('sales', sa.Integer(), nullable=True, comment='总销量'),
    sa.Column('match_order_num', sa.Integer(), nullable=True, comment='出单达人数'),
    sa.Column('sales_content_num', sa.Integer(), nullable=True, comment='出单内容数'),
    sa.Column('format_order_conversion_rate', sa.String(), nullable=True, comment='下单转化率'),
    sa.Column('pv', sa.Integer(), nullable=True, comment='浏览量'),
    sa.Column('author_sale_per', sa.Integer(), nullable=True, comment='达人推广占比'),
    sa.Column('shop_sale_per', sa.Integer(), nullable=True, comment='商家自卖占比'),
    sa.Column('live_sale_per', sa.Integer(), nullable=True, comment='直播销售占比'),
    sa.Column('video_sale_per', sa.Integer(), nullable=True, comment='视频销售占比'),
    sa.Column('visuals_sale_per', sa.Integer(), nullable=True, comment='图文销售占比'),
    sa.Column('shopwindow_sale_per', sa.Integer(), nullable=True, comment='橱窗销售占比'),
    sa.Column('created_at', sa.DateTime(), nullable=True, comment='记录创建时间'),
    sa.PrimaryKeyConstraint('promotion_id')
    )
    op.create_index(op.f('ix_promotion_product_promotion_id'), 'promotion_product', ['promotion_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_promotion_product_promotion_id'), table_name='promotion_product')
    op.drop_table('promotion_product')
    # ### end Alembic commands ###
