"""更新了一些字段

Revision ID: 4f274b682415
Revises: 211c9c139186
Create Date: 2025-09-01 09:34:46.304841

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4f274b682415'
down_revision: Union[str, Sequence[str], None] = '211c9c139186'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('material', sa.Column('is_qianchuan', sa.Integer(), nullable=True, comment='是否为千川素材 可选:0-千川图文;1-千川视频;2-达人图文;3-达人视频'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('material', 'is_qianchuan')
    # ### end Alembic commands ###
