"""增加封面链接字段

Revision ID: 52448debef88
Revises: 69132a205cfc
Create Date: 2025-08-29 10:23:26.417969

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '52448debef88'
down_revision: Union[str, Sequence[str], None] = '69132a205cfc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('app_tokens')
    op.add_column('promotion_product', sa.Column('aweme_id', sa.String(), nullable=True, comment='抖音ID'))
    op.add_column('promotion_product', sa.Column('cover_url', sa.String(), nullable=True, comment='封面链接'))
    op.drop_column('promotion_product', 'account_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('promotion_product', sa.Column('account_id', sa.VARCHAR(), autoincrement=False, nullable=True, comment='选择该品使用的账号'))
    op.drop_column('promotion_product', 'cover_url')
    op.drop_column('promotion_product', 'aweme_id')
    op.create_table('app_tokens',
    sa.Column('id', sa.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('username', sa.VARCHAR(length=128), autoincrement=False, nullable=False),
    sa.Column('userid', sa.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('appid', sa.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('access_token', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('expires_in', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('refresh_token', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('refresh_token_expires_in', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('app_tokens_pkey'))
    )
    # ### end Alembic commands ###
