"""增加qianchuan_douyin_logo、plaft字段

Revision ID: 5597792a5e1d
Revises: 35aaee176c71
Create Date: 2025-09-08 10:28:43.878824

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5597792a5e1d'
down_revision: Union[str, Sequence[str], None] = '35aaee176c71'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('app_tokens', sa.Column('qianchuan_douyin_logo', sa.Integer(), nullable=True))
    op.add_column('app_tokens', sa.Column('platform_id', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('app_tokens', 'platform_id')
    op.drop_column('app_tokens', 'qianchuan_douyin_logo')
    # ### end Alembic commands ###
