"""增加roi字段

Revision ID: 56ab3fbd7010
Revises: 0a3e1b4d2ae0
Create Date: 2025-08-27 10:16:52.457116

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '56ab3fbd7010'
down_revision: Union[str, Sequence[str], None] = '0a3e1b4d2ae0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('promotion_product', sa.Column('roi', sa.Float(), nullable=True, comment='手机端获取的roi数据'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('promotion_product', 'roi')
    # ### end Alembic commands ###
