"""update table

Revision ID: 68431123189a
Revises: a4da64e3d3c3
Create Date: 2025-08-14 08:52:34.895580

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '68431123189a'
down_revision: Union[str, Sequence[str], None] = 'a4da64e3d3c3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sale_content', sa.Column('promotion_id', sa.String(), nullable=True))
    op.drop_column('sale_content', 'raw_data')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sale_content', sa.Column('raw_data', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.drop_column('sale_content', 'promotion_id')
    # ### end Alembic commands ###
