"""增加是否下载字段

Revision ID: 69132a205cfc
Revises: ba1f02801318
Create Date: 2025-08-28 11:28:39.657879

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '69132a205cfc'
down_revision: Union[str, Sequence[str], None] = 'ba1f02801318'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sale_content', sa.Column('is_download', sa.Boolean(), nullable=True, comment='该视频是否下载过'))
    op.drop_column('sale_content', 'is_used')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sale_content', sa.Column('is_used', sa.BOOLEAN(), autoincrement=False, nullable=True, comment='该视频是否使用过'))
    op.drop_column('sale_content', 'is_download')
    # ### end Alembic commands ###
