"""增加roi字段

Revision ID: 694dfe907bad
Revises: 7bb1a70e69cd
Create Date: 2025-08-27 09:36:24.528083

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '694dfe907bad'
down_revision: Union[str, Sequence[str], None] = '7bb1a70e69cd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('promotion_product', sa.Column('roi', sa.Float(), nullable=True, comment='手机端获取的roi数据'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('promotion_product', 'roi')
    # ### end Alembic commands ###
