"""更新

Revision ID: 6b9ad99686a5
Revises: 52448debef88
Create Date: 2025-08-29 11:06:31.594781

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6b9ad99686a5'
down_revision: Union[str, Sequence[str], None] = '52448debef88'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('app_tokens',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('username', sa.String(length=128), nullable=False),
    sa.Column('userid', sa.BigInteger(), nullable=False),
    sa.Column('appid', sa.BigInteger(), nullable=False),
    sa.Column('access_token', sa.Text(), nullable=False),
    sa.Column('expires_in', sa.Integer(), nullable=False),
    sa.Column('refresh_token', sa.Text(), nullable=False),
    sa.Column('refresh_token_expires_in', sa.Integer(), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('material', sa.Column('aweme_id', sa.String(), nullable=True, comment='抖音ID'))
    op.add_column('material', sa.Column('video_cover_id', sa.String(), nullable=True, comment='视频封面ID'))
    op.add_column('material', sa.Column('promotion_card_image_id', sa.String(), nullable=True, comment='推广卡图片ID'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('material', 'promotion_card_image_id')
    op.drop_column('material', 'video_cover_id')
    op.drop_column('material', 'aweme_id')
    op.drop_table('app_tokens')
    # ### end Alembic commands ###
