"""增加acount_id字段

Revision ID: 7bb1a70e69cd
Revises: 9f4d46b1abaa
Create Date: 2025-08-26 17:33:12.101298

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7bb1a70e69cd'
down_revision: Union[str, Sequence[str], None] = '9f4d46b1abaa'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('promotion_product', sa.Column('account_phone', sa.String(), nullable=True, comment='账号手机号'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('promotion_product', 'account_phone')
    # ### end Alembic commands ###
