"""增加material表

Revision ID: 7c1fabb44c9d
Revises: 56ab3fbd7010
Create Date: 2025-08-27 10:32:20.784718

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7c1fabb44c9d'
down_revision: Union[str, Sequence[str], None] = '56ab3fbd7010'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('material',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='自增主键'),
    sa.Column('advertiser_id', sa.String(), nullable=True, comment='广告主ID'),
    sa.Column('promotion_id', sa.String(), nullable=True, comment='推广ID'),
    sa.Column('product_id', sa.String(), nullable=True, comment='商品ID'),
    sa.Column('qianchuan_id', sa.String(), nullable=True, comment='千川ID'),
    sa.Column('shop_id', sa.String(), nullable=True, comment='店铺ID'),
    sa.Column('shop_name', sa.String(), nullable=True, comment='店铺名称'),
    sa.Column('video_path', sa.String(), nullable=True, comment='视频路径'),
    sa.Column('video_name', sa.String(), nullable=True, comment='视频名称'),
    sa.Column('is_aigc', sa.Boolean(), nullable=True, comment='是否AIGC生成'),
    sa.Column('use_status', sa.Boolean(), nullable=True, comment='使用状态'),
    sa.Column('is_qianchuan', sa.Boolean(), nullable=True, comment='是否为千川端素材'),
    sa.Column('use_at', sa.DateTime(), nullable=True, comment='使用时间'),
    sa.Column('created_at', sa.DateTime(), nullable=True, comment='创建时间'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_material_advertiser_id'), 'material', ['advertiser_id'], unique=False)
    op.create_index(op.f('ix_material_promotion_id'), 'material', ['promotion_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_material_promotion_id'), table_name='material')
    op.drop_index(op.f('ix_material_advertiser_id'), table_name='material')
    op.drop_table('material')
    # ### end Alembic commands ###
