"""去除广告主ID索引

Revision ID: 859f6dd826c2
Revises: 86f363179189
Create Date: 2025-08-27 11:35:18.258850

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '859f6dd826c2'
down_revision: Union[str, Sequence[str], None] = '86f363179189'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_material_advertiser_id'), table_name='material')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_material_advertiser_id'), 'material', ['advertiser_id'], unique=False)
    # ### end Alembic commands ###
