"""增加content_id的索引

Revision ID: 86f363179189
Revises: c71987bea53a
Create Date: 2025-08-27 11:31:32.893679

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '86f363179189'
down_revision: Union[str, Sequence[str], None] = 'c71987bea53a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('material_content_id_key'), 'material', type_='unique')
    op.create_index(op.f('ix_material_content_id'), 'material', ['content_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_material_content_id'), table_name='material')
    op.create_unique_constraint(op.f('material_content_id_key'), 'material', ['content_id'], postgresql_nulls_not_distinct=False)
    # ### end Alembic commands ###
