"""增加category，roi_check字段

Revision ID: 95453d98b97a
Revises: a1d6de6a97f1
Create Date: 2025-08-25 18:29:43.685580

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '95453d98b97a'
down_revision: Union[str, Sequence[str], None] = 'a1d6de6a97f1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('promotion_product', sa.Column('category', sa.String(), nullable=True, comment='商品类别'))
    op.add_column('promotion_product', sa.Column('roi_check', sa.Integer(), nullable=True, comment='roi检查字段，0为未检查，1为检测中，2为检测通过，3为检测不通过，4为出现错误'))
    op.drop_index(op.f('index_available'), table_name='sale_content')
    op.drop_column('sale_content', 'available')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sale_content', sa.Column('available', sa.INTEGER(), server_default=sa.text('1'), autoincrement=False, nullable=True, comment='可用状态'))
    op.create_index(op.f('index_available'), 'sale_content', ['available'], unique=False)
    op.drop_column('promotion_product', 'roi_check')
    op.drop_column('promotion_product', 'category')
    # ### end Alembic commands ###
