"""增加acount_id字段

Revision ID: 9f4d46b1abaa
Revises: 1f4fe41ddecf
Create Date: 2025-08-26 17:27:31.566381

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9f4d46b1abaa'
down_revision: Union[str, Sequence[str], None] = '1f4fe41ddecf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('promotion_product', sa.Column('account_id', sa.String(), nullable=True, comment='选择该品使用的账号'))
    op.drop_column('promotion_product', 'acount_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('promotion_product', sa.Column('acount_id', sa.VARCHAR(), autoincrement=False, nullable=True, comment='选择该品使用的账号'))
    op.drop_column('promotion_product', 'account_id')
    # ### end Alembic commands ###
