"""增加is_pass字段

Revision ID: a1d6de6a97f1
Revises: 40f241b3736a
Create Date: 2025-08-19 18:02:14.620573

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a1d6de6a97f1'
down_revision: Union[str, Sequence[str], None] = '40f241b3736a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('promotion_product', sa.Column('is_pass', sa.Boolean(), nullable=True, comment='是否通过筛选'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('promotion_product', 'is_pass')
    # ### end Alembic commands ###
