"""create douyin_content table

Revision ID: a4da64e3d3c3
Revises: 
Create Date: 2025-08-13 15:13:06.767851

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a4da64e3d3c3'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sale_content',
    sa.Column('content_id', sa.String(), nullable=False),
    sa.Column('content_type', sa.String(), nullable=True),
    sa.Column('content_title', sa.String(), nullable=True),
    sa.Column('content_cover', sa.String(), nullable=True),
    sa.Column('video_url', sa.String(), nullable=True),
    sa.Column('duration', sa.Integer(), nullable=True),
    sa.Column('cover_url', sa.String(), nullable=True),
    sa.Column('publish_time', sa.DateTime(), nullable=True),
    sa.Column('author_name', sa.String(), nullable=True),
    sa.Column('author_avatar', sa.String(), nullable=True),
    sa.Column('author_sec_id', sa.String(), nullable=True),
    sa.Column('author_level', sa.Integer(), nullable=True),
    sa.Column('author_fans_count', sa.Integer(), nullable=True),
    sa.Column('author_resident', sa.String(), nullable=True),
    sa.Column('share_url', sa.String(), nullable=True),
    sa.Column('sales', sa.Integer(), nullable=True),
    sa.Column('format_sales', sa.String(), nullable=True),
    sa.Column('sales_amount', sa.BigInteger(), nullable=True),
    sa.Column('format_sales_amount', sa.String(), nullable=True),
    sa.Column('like_count', sa.Integer(), nullable=True),
    sa.Column('play_count', sa.BigInteger(), nullable=True),
    sa.Column('order_conversion_rate', sa.Float(), nullable=True),
    sa.Column('format_order_conversion_rate', sa.String(), nullable=True),
    sa.Column('click_rate', sa.Float(), nullable=True),
    sa.Column('comment_count', sa.Integer(), nullable=True),
    sa.Column('share_count', sa.Integer(), nullable=True),
    sa.Column('pcu', sa.Integer(), nullable=True),
    sa.Column('is_self_sale', sa.Boolean(), nullable=True),
    sa.Column('raw_data', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('content_id')
    )
    op.create_index(op.f('ix_sale_content_content_id'), 'sale_content', ['content_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_sale_content_content_id'), table_name='sale_content')
    op.drop_table('sale_content')
    # ### end Alembic commands ###
