"""增加is_used字段

Revision ID: a7ecf5004ae2
Revises: 95453d98b97a
Create Date: 2025-08-26 09:37:59.654867

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a7ecf5004ae2'
down_revision: Union[str, Sequence[str], None] = '95453d98b97a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sale_content', sa.Column('is_used', sa.Boolean(), nullable=True, comment='该视频是否使用过'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('sale_content', 'is_used')
    # ### end Alembic commands ###
