"""增加video_id、hide_in_aweme字段

Revision ID: ba1f02801318
Revises: 859f6dd826c2
Create Date: 2025-08-28 09:17:02.702144

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ba1f02801318'
down_revision: Union[str, Sequence[str], None] = '859f6dd826c2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('material', sa.Column('video_id', sa.String(), nullable=True, comment='我们上传的视频ID'))
    op.add_column('material', sa.Column('hide_in_aweme', sa.Boolean(), nullable=True, comment='抖音主页可见性设置'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('material', 'hide_in_aweme')
    op.drop_column('material', 'video_id')
    # ### end Alembic commands ###
