"""增加content_id的唯一性

Revision ID: c71987bea53a
Revises: 7c1fabb44c9d
Create Date: 2025-08-27 11:29:21.525763

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c71987bea53a'
down_revision: Union[str, Sequence[str], None] = '7c1fabb44c9d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('material', sa.Column('content_id', sa.String(), nullable=True, comment='视频的唯一ID'))
    op.add_column('material', sa.Column('usable', sa.Boolean(), nullable=True, comment='是否可以使用'))
    op.create_unique_constraint(None, 'material', ['content_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'material', type_='unique')
    op.drop_column('material', 'usable')
    op.drop_column('material', 'content_id')
    # ### end Alembic commands ###
